# Generated by Django 3.2.6 on 2021-08-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminid', models.IntegerField()),
                ('adminname', models.CharField(max_length=20)),
                ('adminpass', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('cateid', models.BigAutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('userid', models.IntegerField()),
                ('cusid', models.BigAutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('contactname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('oid', models.BigAutoField(primary_key=True, serialize=False)),
                ('odate', models.DateField()),
                ('shipdate', models.DateField()),
                ('ostatus', models.CharField(max_length=20)),
                ('totalprice', models.IntegerField()),
                ('cusid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('sid', models.BigAutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('semail', models.CharField(max_length=20)),
                ('sphno', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
                ('unitsinstock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=20)),
                ('defaultimage', models.CharField(max_length=500)),
                ('cateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categories')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ordetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='images12',
            fields=[
                ('imgid', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='Images')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='cusinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusinfoid', models.IntegerField()),
                ('country', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('phno', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('cusid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('noproducts', models.IntegerField()),
                ('tprice', models.IntegerField()),
                ('cusid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='billing',
            fields=[
                ('bid', models.BigAutoField(primary_key=True, serialize=False)),
                ('cardname', models.CharField(max_length=20)),
                ('cardnum', models.IntegerField()),
                ('expmonth', models.IntegerField()),
                ('expyear', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('cusid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
    ]
