# Generated by Django 3.2.6 on 2021-09-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_admin4_billing_cart_categories_cusinfo_customer_images12_order_ordetails_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cusinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='cusinfo',
            name='cusinfoid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
