# Generated by Django 3.2.6 on 2021-09-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210903_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addressid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.cusinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cardid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.billing'),
            preserve_default=False,
        ),
    ]
