from django.urls import path
from . import views
urlpatterns = [
    path('index',views.page1),
    path('cart',views.loadCart),
    path('left',views.page3),
    path('right',views.page4),
    path('switch',views.page5),
    path('light',views.page6),
    path('bell',views.page7),
    path('smoke',views.page8),
    path('',views.page9),
    path('profile',views.profile),
    path('savecart',views.storecart),
    path('link2',views.login),
    path('logout', views.userlogout),
    path('adminlogout', views.adminlogout),
    path('link3',views.admin),
    path('link4',views.getproducts),
    path('link6',views.products),
    path('link7',views.productsdisplay),
    path('delete',views.remove),
    path('modify',views.getProductById),
    path('update',views.update),
    path('loadproducts',views.loadproducts),
    path('link5',views.pdetails,name="pdetails"),
    path('login', views.createlog),
    path('adminlogin', views.adminlogin),
    path('details', views.addproduct),
    path('signup', views.signup),
    path('addSupplier', views.AddSupplier),
    path('manageSuppliers', views.ManageSuppliers),
    path('modifySupplier', views.ModifySupplier),
    path('deleteSupplier', views.DeleteSupplier),
    path('addCategory', views.AddCategory),
    path('manageCategories', views.ManageCategories),
    path('modifyCategory', views.ModifyCategory),
    path('deleteCategory', views.DeleteCategory),
    path('manageAddress', views.ManageAddress),
    path('addAddress', views.AddAddress),
    path('modifyAddress', views.ModifyAddress),
    path('deleteAddress', views.DeleteAddress),
    path('manageCard', views.ManageCard),
    path('addCard', views.AddCard),
    path('modifyCard', views.ModifyCard),
    path('deleteCard', views.DeleteCard),
    path('getAddresses', views.GetAddresses),
    path('getCards', views.GetCards),
    path('placeOrder', views.placeOrder),
    path('OrderStatus', views.OrderStatus),
    path('AdminOrderStatus', views.AdminOrderStatus),
    path('modifyOrder', views.ModifyOrder),
    path('removeFromCart', views.removeFromCart)
]